# Generated by Django 4.2 on 2023-04-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyctlg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9)),
                ('datetime', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.company')),
                ('ourfirm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.ourfirm')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9)),
                ('datetime', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.company')),
                ('ourfirm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.ourfirm')),
            ],
        ),
    ]
