# Generated by Django 4.2 on 2023-04-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_receipt_ourfirm_shipment_ourfirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='ourfirm',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ourfirm',
        ),
    ]
