# Generated by Django 4.2 on 2023-04-19 18:06

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('companyctlg', '0010_ourfirm'),
        ('document', '0006_remove_receipt_ourfirm_remove_shipment_ourfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ourfirm',
            field=models.ForeignKey(default=document.models.ourfirm_default, on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.ourfirm'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ourfirm',
            field=models.ForeignKey(default=document.models.ourfirm_default, on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.ourfirm'),
        ),
    ]
