# Generated by Django 4.2 on 2023-04-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingctlg', '0005_uom'),
        ('document', '0007_receipt_ourfirm_shipment_ourfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='document.shipment')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thingctlg.thing', verbose_name='Product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thingctlg.uom', verbose_name='UoM')),
            ],
            options={
                'unique_together': {('shipment', 'thing')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='document.receipt')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thingctlg.thing', verbose_name='Material')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thingctlg.uom', verbose_name='UoM')),
            ],
            options={
                'unique_together': {('receipt', 'thing')},
            },
        ),
    ]
