# Generated by Django 4.2 on 2023-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_receipt_ourfirm_remove_shipment_ourfirm'),
        ('companyctlg', '0002_alter_ourfirm_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ourfirm',
        ),
    ]
