# Generated by Django 4.2 on 2023-04-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyctlg', '0003_delete_ourfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourfirm',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='companyctlg.company')),
            ],
        ),
    ]
