# Generated by Django 4.2 on 2023-04-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_receipt_ourfirm_remove_shipment_ourfirm'),
        ('companyctlg', '0006_alter_ourfirm_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ourfirm',
        ),
    ]
