# Generated by Django 4.2 on 2023-04-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyctlg', '0007_delete_ourfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='companyctlg.company')),
            ],
        ),
    ]
