# Generated by Django 4.2 on 2023-04-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_receipt_ourfirm_remove_shipment_ourfirm'),
        ('companyctlg', '0008_ourfirm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ourfirm',
        ),
    ]
