# Generated by Django 4.2 on 2023-04-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingctlg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thingctlg.thingfolder'),
        ),
    ]
