# Generated by Django 4.2 on 2023-04-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingctlg', '0003_uom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UoM',
        ),
    ]
