# Generated by Django 4.2 on 2023-04-19 16:05

from django.db import migrations, models
import thingctlg.models


class Migration(migrations.Migration):

    dependencies = [
        ('thingctlg', '0004_delete_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('code', models.CharField(default=thingctlg.models.uom_code_default, max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
